### PR TITLE
Add file dependency config

### PR DESCRIPTION
**Pull request by wfleming**
Specify files to download in YAML.

```
dependencies:
  files:
    - http://example.com/config.json
    - url: https://example.com/other_config.yml
      path: local_path.yml

engines:
  ...
```

Validates URLs & paths.

cc @codeclimate/review

### CODE REVIEW

**Comment by toddmohney** [comment]
:point_up_2: is this showing 2 ways to do pull the file? the second showing how to direct it to a particular location?

What do you think about having a single extensible interface, instead?
```
# simple example
files:
  - url: http://things.com/file.json

# copy to location example
files:
  - url: http://things.com/file.json
    path: some/path/to/my-file.json
```

**Comment by wfleming** [comment]
@toddmohney Good catch: my rough implementation in builder did handle the `url: foo` case without a path, but I didn't transfer that ability over. I've done so, and added another spec.

Supporting a plain string is also desirable since it's the simplest possible thing people can type. So we support all three permutations now.

```
dependencies:
  files:
    - http://example.com/config.json
    - url: https://example.com/inferred_path.yml
    - url: https://example.com/other_config.yml
      path: local_path.yml
```

**Comment by nporteschaikin** [comment]
lgtm

**Comment by toddmohney** [comment]
@wfleming cool, looks good. 

Building a solid interface is crucial for a number of reasons:
- end user usability (obviously)
- a stable/extensible interface allows us to change things behind the scenes without end user disruption

I think I'm gonna start putting a talk together about that for next week's lunchylearn

**Pull request merged**
